# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_auto_20151126_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='params',
            field=models.TextField(blank=True),
        ),
    ]
